### ISSUE TITLE
"Addon appears to be corrupted"

### ISSUE THREAD

**Issue by MrTheyes** [iKingNinja/Accounts-manager#9]
1. Downloaded file
2. Went to addons web
3. Click on zip file
4. Message says the title

expected to accept it
![image](https://user-images.githubusercontent.com/122626253/212567570-8ef9e9f7-e7e6-463d-bdaa-97a18d20aaeb.png)
nothing on the console
Firefox
108.0.2
(idk if ive done anything wrong with the template or with the file, Yeah)

**Comment by iKingNinja** [comment]
Did you install it from Firefox's add-ons store? If not, did you download the correct file from the releases page? Did you select manifest.json when installing it?

**Comment by MrTheyes** [comment]
its all good now, i got the addon from the store, it was kinda obscure since theres only 1 reference to roblox but thats fine, as long as it works amiright? cheers tho.

**Comment by iKingNinja** [comment]
It was probably because you installed it incorrectly, when installing add-ons on Firefox make sure to select manifest.json.
